#!/usr/bin/env python3
"""Oracle debug stages for cuda_dldn_engine_swin_enc0_kernel's phases 8..22.

Each stage is a (file line after which the store block goes, registers in order) tuple for
kernels/tex/make_ptx.py's SWIN_DEBUG_STAGES, so D4R_RRSWIN_DEBUG=p8 (p8o, p9, p10, ...)
builds NVIDIA's own body with that stage's registers stored into the plane arena, which
kernels/rr/rrswin_enc0.hip's D4R_RRSWIN_DEBUG_STAGE reproduces from its own registers.

GENERATED by kernels/tools/swin_stages.py from the corpus PTX -- do not edit.  An
accumulator stage keeps the mma whose D pair no other mma of the phase reads as its C (the
last k-step of an accumulating chain) and lists the tiles in mma order: m-tile major,
n-tile minor, the row pair (row g, row g+8) at each base.  An operand stage lists the A
fragments, the B fragment pairs and the C seeds as the mma read them.
"""


def swin_pairs(bases):
    """One register pair per base: a tile's (row g, row g+8) D registers."""
    return sum(([f"%r{b + rh}" for rh in (0, 1)] for b in bases), [])


def swin_quads(bases):
    """One A fragment per base: four b32."""
    return sum(([f"%r{b + o}" for o in range(4)] for b in bases), [])


def stages():
    """The stage table: name -> (splice line, registers)."""
    return {
        # phase 8: 24 mma, 24 output tiles, splice after file line 19934
        "p8": (19934, swin_pairs([6503, 6513, 6523, 6533, 6543, 6553, 6563, 6573, 6583, 6593, 6603, 6613, 6623, 6633, 6643, 6653, 6663, 6673, 6683, 6693, 6703, 6713, 6723, 6733])),
            # HAND-ADDED (not produced by kernels/tools/swin_stages.py): phase 8's 32 operand registers
    # followed by its 48 accumulator registers, so one capture gives a phase's inputs and its
    # output from the same run -- the pilot needs both from one frame.  Both sets are live at
    # line 19934 (the operands because phase 8's mma have not overwritten them, the
    # accumulators because the store is after its last mma).  Slot is 16384 for 80 registers.
    "p8c": (19934, ['%r6784', '%r6785', '%r6786', '%r6787', '%r6824', '%r6825', '%r6826', '%r6827', '%r6864', '%r6865', '%r6866', '%r6867', '%r6904', '%r6905', '%r6906', '%r6907', '%r6944', '%r6945', '%r6946', '%r6947', '%r6984', '%r6985', '%r6986', '%r6987', '%r6495', '%r6496', '%r6497', '%r6498', '%r6499', '%r6500', '%r6501', '%r6502', '%r6503', '%r6504', '%r6513', '%r6514', '%r6523', '%r6524', '%r6533', '%r6534', '%r6543', '%r6544', '%r6553', '%r6554', '%r6563', '%r6564', '%r6573', '%r6574', '%r6583', '%r6584', '%r6593', '%r6594', '%r6603', '%r6604', '%r6613', '%r6614', '%r6623', '%r6624', '%r6633', '%r6634', '%r6643', '%r6644', '%r6653', '%r6654', '%r6663', '%r6664', '%r6673', '%r6674', '%r6683', '%r6684', '%r6693', '%r6694', '%r6703', '%r6704', '%r6713', '%r6714', '%r6723', '%r6724', '%r6733', '%r6734']),
"p8o": (19934, swin_quads([6784, 6824, 6864, 6904, 6944, 6984]) + swin_pairs([6495, 6497, 6499, 6501])),   # A fragments, B fragment pairs; 32 registers
        # phase 9: 24 mma, 24 output tiles, splice after file line 20115
        "p9": (20115, swin_pairs([6752, 6762, 6772, 6782, 6792, 6802, 6812, 6822, 6832, 6842, 6852, 6862, 6872, 6882, 6892, 6902, 6912, 6922, 6932, 6942, 6952, 6962, 6972, 6982])),
        "p9o": (20115, swin_quads([6784, 6824, 6864, 6904, 6944, 6984]) + swin_pairs([6744, 6746, 6748, 6750])),   # A fragments, B fragment pairs; 32 registers
        # phase 10: 48 mma, 48 output tiles, splice after file line 20832
        "p10": (20832, swin_pairs([7169, 7179, 7189, 7199, 7209, 7219, 7229, 7239, 7249, 7259, 7269, 7279, 7289, 7299, 7309, 7319, 7329, 7339, 7349, 7359, 7369, 7379, 7389, 7399, 7409, 7419, 7429, 7439, 7449, 7459, 7469, 7479, 7489, 7499, 7509, 7519, 7529, 7539, 7549, 7559, 7569, 7579, 7589, 7599, 7609, 7619, 7629, 7639])),
        "p10o": (20832, swin_quads([7281, 7401, 7521, 7641]) + swin_pairs([7535, 7545, 7555, 7565, 7575, 7585, 7595, 7605, 7615, 7625, 7635, 7645]) + ["%r6993", "%r6994", "%r6995", "%r6996", "%r7009", "%r7010", "%r7011", "%r7012", "%r7025", "%r7026", "%r7027", "%r7028", "%r7041", "%r7042", "%r7043", "%r7044", "%r7057", "%r7058", "%r7059", "%r7060", "%r7073", "%r7074", "%r7075", "%r7076", "%r6997", "%r6998", "%r6999", "%r7000", "%r7013", "%r7014", "%r7015", "%r7016", "%r7029", "%r7030", "%r7031", "%r7032", "%r7045", "%r7046", "%r7047", "%r7048", "%r7061", "%r7062", "%r7063", "%r7064", "%r7077", "%r7078", "%r7079", "%r7080", "%r7001", "%r7002", "%r7003", "%r7004", "%r7017", "%r7018", "%r7019", "%r7020", "%r7033", "%r7034", "%r7035", "%r7036", "%r7049", "%r7050", "%r7051", "%r7052", "%r7065", "%r7066", "%r7067", "%r7068", "%r7081", "%r7082", "%r7083", "%r7084", "%r7005", "%r7006", "%r7007", "%r7008", "%r7021", "%r7022", "%r7023", "%r7024", "%r7037", "%r7038", "%r7039", "%r7040", "%r7053", "%r7054", "%r7055", "%r7056", "%r7069", "%r7070", "%r7071", "%r7072", "%r7085", "%r7086", "%r7087", "%r7088"]),   # A fragments, B fragment pairs, C seeds; 136 registers
        # phase 11: 48 mma, 16 output tiles, splice after file line 31306
        "p11": (31306, swin_pairs([10455, 10465, 10515, 10525, 10575, 10585, 10635, 10645, 10695, 10705, 10755, 10765, 10815, 10825, 10875, 10885])),
        "p11o": (31306, swin_quads([10487, 10507, 10527, 10607, 10627, 10647, 10727, 10747, 10767, 10847, 10867, 10887]) + swin_pairs([10781, 10791, 10801, 10811, 10821, 10831, 10841, 10851, 10861, 10871, 10881, 10891])),   # A fragments, B fragment pairs; 72 registers
        # phase 12: 16 mma, 16 output tiles, splice after file line 31543
        "p12": (31543, swin_pairs([10936, 10946, 10956, 10966, 10976, 10986, 10996, 11006, 11016, 11026, 11036, 11046, 11056, 11066, 11076, 11086])),
        "p12o": (31543, swin_quads([10968, 11008, 11048, 11088]) + swin_pairs([10896, 10898, 10900, 10902]) + ["%r6334", "%r6335", "%r6344", "%r6345", "%r6354", "%r6355", "%r6364", "%r6365", "%r6374", "%r6375", "%r6384", "%r6385", "%r6394", "%r6395", "%r6404", "%r6405", "%r6414", "%r6415", "%r6424", "%r6425", "%r6434", "%r6435", "%r6444", "%r6445", "%r6454", "%r6455", "%r6464", "%r6465", "%r6474", "%r6475", "%r6484", "%r6485"]),   # A fragments, B fragment pairs, C seeds; 56 registers
        # phase 13: 16 mma, 16 output tiles, splice after file line 33797
        "p13": (33797, swin_pairs([11424, 11434, 11444, 11454, 11464, 11474, 11484, 11494, 11504, 11514, 11524, 11534, 11544, 11554, 11564, 11574])),
        "p13o": (33797, swin_quads([11456, 11496, 11536, 11576]) + swin_pairs([11383, 11385, 11387, 11389]) + ["%r11553", "%r11563", "%r11573", "%r11583"]),   # A fragments, B fragment pairs, C seeds; 28 registers
        # phase 14: 16 mma, 16 output tiles, splice after file line 36260
        "p14": (36260, swin_pairs([12555, 12565, 12575, 12585, 12595, 12605, 12615, 12625, 12635, 12645, 12655, 12665, 12675, 12685, 12695, 12705])),
        "p14o": (36260, swin_quads([12587, 12627, 12667, 12707]) + swin_pairs([12514, 12516, 12518, 12520]) + ["%r12563", "%r12564", "%r12573", "%r12574", "%r12583", "%r12584", "%r12593", "%r12594", "%r12603", "%r12604", "%r12613", "%r12614", "%r12623", "%r12624", "%r12633", "%r12634", "%r12643", "%r12644", "%r12653", "%r12654", "%r12663", "%r12664", "%r12673", "%r12674", "%r12683", "%r12684", "%r12693", "%r12694", "%r12703", "%r12704", "%r12713", "%r12714"]),   # A fragments, B fragment pairs, C seeds; 56 registers
        # phase 15: 16 mma, 16 output tiles, splice after file line 36508
        "p15": (36508, swin_pairs([12757, 12767, 12777, 12787, 12797, 12807, 12817, 12827, 12837, 12847, 12857, 12867, 12877, 12887, 12897, 12907])),
        "p15o": (36508, swin_quads([12789, 12829, 12869, 12909]) + swin_pairs([12716, 12718, 12720, 12722]) + ["%r12886", "%r12896", "%r12906", "%r12916"]),   # A fragments, B fragment pairs, C seeds; 28 registers
        # phase 16: 16 mma, 16 output tiles, splice after file line 38668
        "p16": (38668, swin_pairs([13887, 13897, 13907, 13917, 13927, 13937, 13947, 13957, 13967, 13977, 13987, 13997, 14007, 14017, 14027, 14037])),
        "p16o": (38668, swin_quads([13919, 13959, 13999, 14039]) + swin_pairs([13847, 13849, 13851, 13853]) + ["%r12555", "%r12556", "%r12565", "%r12566", "%r12575", "%r12576", "%r12585", "%r12586", "%r12595", "%r12596", "%r12605", "%r12606", "%r12615", "%r12616", "%r12625", "%r12626", "%r12635", "%r12636", "%r12645", "%r12646", "%r12655", "%r12656", "%r12665", "%r12666", "%r12675", "%r12676", "%r12685", "%r12686", "%r12695", "%r12696", "%r12705", "%r12706"]),   # A fragments, B fragment pairs, C seeds; 56 registers
        # phase 17: 16 mma, 16 output tiles, splice after file line 38916
        "p17": (38916, swin_pairs([14089, 14099, 14109, 14119, 14129, 14139, 14149, 14159, 14169, 14179, 14189, 14199, 14209, 14219, 14229, 14239])),
        "p17o": (38916, swin_quads([14121, 14161, 14201, 14241]) + swin_pairs([14048, 14050, 14052, 14054]) + ["%r14218", "%r14228", "%r14238", "%r14248"]),   # A fragments, B fragment pairs, C seeds; 28 registers
        # phase 18: 16 mma, 16 output tiles, splice after file line 41076
        "p18": (41076, swin_pairs([15219, 15229, 15239, 15249, 15259, 15269, 15279, 15289, 15299, 15309, 15319, 15329, 15339, 15349, 15359, 15369])),
        "p18o": (41076, swin_quads([15251, 15291, 15331, 15371]) + swin_pairs([15179, 15181, 15183, 15185]) + ["%r13887", "%r13888", "%r13897", "%r13898", "%r13907", "%r13908", "%r13917", "%r13918", "%r13927", "%r13928", "%r13937", "%r13938", "%r13947", "%r13948", "%r13957", "%r13958", "%r13967", "%r13968", "%r13977", "%r13978", "%r13987", "%r13988", "%r13997", "%r13998", "%r14007", "%r14008", "%r14017", "%r14018", "%r14027", "%r14028", "%r14037", "%r14038"]),   # A fragments, B fragment pairs, C seeds; 56 registers
        # phase 19: 16 mma, 16 output tiles, splice after file line 41324
        "p19": (41324, swin_pairs([15421, 15431, 15441, 15451, 15461, 15471, 15481, 15491, 15501, 15511, 15521, 15531, 15541, 15551, 15561, 15571])),
        "p19o": (41324, swin_quads([15453, 15493, 15533, 15573]) + swin_pairs([15380, 15382, 15384, 15386]) + ["%r15550", "%r15560", "%r15570", "%r15580"]),   # A fragments, B fragment pairs, C seeds; 28 registers
        # phase 20: 16 mma, 16 output tiles, splice after file line 43484
        "p20": (43484, swin_pairs([16551, 16561, 16571, 16581, 16591, 16601, 16611, 16621, 16631, 16641, 16651, 16661, 16671, 16681, 16691, 16701])),
        "p20o": (43484, swin_quads([16583, 16623, 16663, 16703]) + swin_pairs([16511, 16513, 16515, 16517]) + ["%r15219", "%r15220", "%r15229", "%r15230", "%r15239", "%r15240", "%r15249", "%r15250", "%r15259", "%r15260", "%r15269", "%r15270", "%r15279", "%r15280", "%r15289", "%r15290", "%r15299", "%r15300", "%r15309", "%r15310", "%r15319", "%r15320", "%r15329", "%r15330", "%r15339", "%r15340", "%r15349", "%r15350", "%r15359", "%r15360", "%r15369", "%r15370"]),   # A fragments, B fragment pairs, C seeds; 56 registers
        # phase 21: 32 mma, 8 output tiles, splice after file line 44258
        "p21": (44258, swin_pairs([17298, 17308, 17378, 17388, 17458, 17468, 17538, 17548])),
        "p21o": (44258, swin_quads([17490, 17510, 17530, 17550]) + swin_pairs([17173, 17175, 17177, 17179, 17181, 17183, 17185, 17187, 17189, 17191, 17193, 17195, 17197, 17199, 17201, 17203, 17205, 17207, 17209, 17211, 17213, 17215, 17217, 17219, 17221, 17223, 17225, 17227, 17229, 17231, 17233, 17235]) + ["%r17247", "%r17257", "%r17327", "%r17337", "%r17407", "%r17417", "%r17487", "%r17497"]),   # A fragments, B fragment pairs, C seeds; 88 registers
        # phase 22: 8 mma, 8 output tiles, splice after file line 44527
        "p22": (44527, swin_pairs([17634, 17644, 17654, 17664, 17674, 17684, 17694, 17704])),
        "p22o": (44527, swin_quads([262, 266, 270, 274]) + swin_pairs([17629, 17631]) + ["%r17703", "%r17713"] + ["%r10854", "%r10854"]),   # A fragments, B fragment pairs, C seeds; 24 registers
    }
