#!/usr/bin/env python3
"""Emit the oracle debug stages for cuda_dldn_engine_swin_enc0_kernel, phases 8..22.

For each phase it reads NVIDIA's PTX, keeps the mma whose D pair is not another mma's
C operand inside the same phase (the last k-step of an accumulating chain), and lists
those tiles in mma order, which is m-tile major and n-tile minor -- the order the
native body's stage_regs() writes.  Operand stages list the phase's A fragments, B
fragment pairs and C seeds as the mma read them.

Writes kernels/rr/swin_enc0_debug_stages.py, which make_ptx.py folds into its own
SWIN_DEBUG_STAGES.
"""
import re
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "rr"))
import rr_layer_spec as R  # noqa: E402

ENTRY = "cuda_dldn_engine_swin_enc0_kernel"
ZERO_C = "%r10854"          # mov.u32 %r10854, 0 (PTX line 3920): the unfused phases' C
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "rr",
                   "swin_enc0_debug_stages.py")

PHASES = {
    8: (8057, 8080), 9: (8088, 8111), 10: (8283, 8330), 11: (12169, 12216),
    12: (12272, 12287), 13: (13175, 13190), 14: (13900, 13915), 15: (13980, 13995),
    16: (14596, 14611), 17: (14676, 14691), 18: (15292, 15307), 19: (15372, 15387),
    20: (15988, 16003), 21: (16418, 16449), 22: (16607, 16614),
}

HEADER = '''#!/usr/bin/env python3
"""Oracle debug stages for cuda_dldn_engine_swin_enc0_kernel's phases 8..22.

Each stage is a (file line after which the store block goes, registers in order) tuple for
kernels/tex/make_ptx.py's SWIN_DEBUG_STAGES, so D4R_RRSWIN_DEBUG=p8 (p8o, p9, p10, ...)
builds NVIDIA's own body with that stage's registers stored into the plane arena, which
kernels/rr/rrswin_enc0.hip's D4R_RRSWIN_DEBUG_STAGE reproduces from its own registers.

GENERATED by kernels/tools/swin_stages.py from the corpus PTX -- do not edit.  An
accumulator stage keeps the mma whose D pair no other mma of the phase reads as its C (the
last k-step of an accumulating chain) and lists the tiles in mma order: m-tile major,
n-tile minor, the row pair (row g, row g+8) at each base.  An operand stage lists the A
fragments, the B fragment pairs and the C seeds as the mma read them.
"""


def swin_pairs(bases):
    """One register pair per base: a tile's (row g, row g+8) D registers."""
    return sum(([f"%r{b + rh}" for rh in (0, 1)] for b in bases), [])


def swin_quads(bases):
    """One A fragment per base: four b32."""
    return sum(([f"%r{b + o}" for o in range(4)] for b in bases), [])


def stages():
    """The stage table: name -> (splice line, registers)."""
    return {
'''


def phase_mmas(stmts, p):
    lo, hi = PHASES[p]
    out = []
    for s in stmts:
        if not s.is_mma or not (lo <= s.idx <= hi):
            continue
        r = re.findall(r"%r\d+", s.text)
        out.append(dict(D=(r[0], r[1]), A=tuple(r[2:6]), B=(r[6], r[7]), C=(r[8], r[9]),
                        line=s.line))
    return out


def outputs(mmas):
    """The last k-step of every chain: the mma whose D pair no other mma reads as its C."""
    cs = set()
    for m in mmas:
        cs.update(m["C"])
    return [m for m in mmas if m["D"][0] not in cs and m["D"][1] not in cs]


def dbase(mmas):
    return [int(m["D"][0][2:]) for m in outputs(mmas)]


def abase(mmas):
    seen, out = set(), []
    for m in mmas:
        if m["A"][0] in seen:
            continue
        seen.add(m["A"][0])
        out.append(int(m["A"][0][2:]))
    return out


def bbase(mmas):
    seen, out = set(), []
    for m in mmas:
        if m["B"][0] in seen:
            continue
        seen.add(m["B"][0])
        out.append(int(m["B"][0][2:]))
    return out


def cseed(mmas):
    """The distinct C registers that are not another mma's D inside the same phase (an
    accumulating chain's previous step is not a seed), in first-appearance order."""
    ds = set()
    for m in mmas:
        ds.update(m["D"])
    seen, out = set(), []
    for m in mmas:
        for r in m["C"]:
            if r in seen or r in ds or r == ZERO_C:
                continue
            seen.add(r)
            out.append(r)
    return out


def nums(xs):
    return ", ".join(str(x) for x in xs)


def entries(p, mmas, after):
    """The two dict entries of one phase: its output tiles, and its mma operands."""
    d, a, b, cs = dbase(mmas), abase(mmas), bbase(mmas), cseed(mmas)
    parts = [f"swin_quads([{nums(a)}])", f"swin_pairs([{nums(b)}])"]
    n = 4 * len(a) + 2 * len(b)
    kinds = "A fragments, B fragment pairs"
    if cs:
        parts.append("[" + ", ".join(f'"{r}"' for r in cs) + "]")
        n += len(cs)
        kinds += ", C seeds"
    pad = -n % 4      # swin_debug_block stores four registers per v4, so pad with the zero
    if pad:
        parts.append("[" + ", ".join([f'"{ZERO_C}"'] * pad) + "]")
        n += pad
    return [f"        # phase {p}: {len(mmas)} mma, {len(d)} output tiles, "
            f"splice after file line {after}",
            f'        "p{p}": ({after}, swin_pairs([{nums(d)}])),',
            f'        "p{p}o": ({after}, {" + ".join(parts)}),'
            f"   # {kinds}; {n} registers"]


def main():
    path, entry_name = R.resolve("enc0", None, None)
    lines = open(path).read().split("\n")
    first, last = next((a, b) for (nm, a, b) in R.find_entries(lines) if nm == entry_name)
    stmts, _ = R.linearise(lines, first, last)
    body = []
    for p in sorted(PHASES):
        mmas = phase_mmas(stmts, p)
        after = max(m["line"] for m in mmas) + 3
        assert lines[after - 1].rstrip().endswith(";"), lines[after - 1]
        body.extend(entries(p, mmas, after))
    with open(OUT, "w") as f:
        f.write(HEADER + "\n".join(body) + "\n    }\n")


if __name__ == "__main__":
    main()